name:                safe-buffer-monad
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/dcastro/safe-buffer-monad#readme
license:             BSD3
author:              Diogo Castro
maintainer:          dc@diogocastro.com
copyright:           2017 Diogo Castro
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - exceptions
  - unliftio
  - safe-exceptions

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -fwarn-tabs
    - -O2
    - -fdefer-typed-holes

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - safe-buffer-monad
    - hspec
    - QuickCheck
