name:                safe-buffer-monad
version:             0.1.0
synopsis:            A monadic buffer resilient to exceptions
description:         Please see README.md
homepage:            https://github.com/dcastro/safe-buffer-monad#readme
github:              dcastro/safe-buffer-monad
license:             BSD3
author:              Diogo Castro
maintainer:          dc@diogocastro.com
copyright:           2017 Diogo Castro
category:            Control
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - mtl >= 2.0 && < 3.0
  - stm >= 2.0 && < 3.0
  - safe-exceptions >= 0.1 && < 1.0

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -fwarn-tabs

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - safe-buffer-monad
    - hspec
    - unliftio
